# fly.toml file generated for throbbing-snowflake-655 on 2023-04-14T11:27:41+10:00

app = "throbbing-snowflake-655"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "syd"
processes = []

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
